### ISSUE TITLE
plants do not grow when clustered in anything other than peaceful

### ISSUE THREAD

**Issue by cockatiel-navi** [Konlii/OrganicCreepers#2]
when close together they grow to last stage and stop spawning

**Comment by Konlii** [comment]
The plants check within a certain range and if there are already more creepers than the max spawn limit for that biome (4 for creepers unless the specific biome overrides that), the plants will not spawn more creepers.

This is to stop infinite creepers from spawning all on top of each other.  But what I can do is add a config item so that you can change how far out each plant checks.

**Comment by Konlii** [comment]
v1.0.1 uploaded
if you set creeperCheckDistance to 0 creepers should continue to spawn forever

**Comment by cockatiel-navi** [comment]
oh yea i forgot about that! thanks. well made mod!
